include: package:lint/strict.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
    - "**/*.config.dart"

linter:
  rules:
    prefer_single_quotes: true
    omit_local_variable_types: true
    omit_obvious_local_variable_types: true
    omit_obvious_property_types: true
    unnecessary_lambdas: true
    sort_constructors_first: true
    type_annotate_public_apis: false
    unnecessary_getters_setters: false
    use_setters_to_change_properties: false
    avoid_setters_without_getters: false

formatter:
  page_width: 120
  trailing_commas: preserve
