name: url_shortener
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  auto_route: ^10.1.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  duration: ^4.0.3
  envied: ^1.3.0
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  validators: ^3.0.0

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  envied_generator: ^1.3.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  lint: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500

flutter_launcher_icons:
  image_path: "assets/images/compass.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#16262E"
  android: true
  ios: true
